apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: flask-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm

  namespaceSelector:
    matchNames:
      - flask

  endpoints:
    - port: http
      path: /metrics
      interval: 30s