apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: flask-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/aleemahmad0508/mcp-project.git
    targetRevision: master
    path: flask-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true